CREATE TABLE `members` (
	 `member_id` INT NOT NULL PRIMARY KEY  AUTO_INCREMENT,
	 `username` VARCHAR(225) NOT NULL,
	 `firstname` VARCHAR(225) NOT NULL,
	 `lastname` VARCHAR(225) NOT NULL,
	 `phone` VARCHAR(15) NOT NULL,
	 `email` VARCHAR(225) CHARACTER SET utf8 NOT NULL,
	 `address` VARCHAR(225) NOT NULL,
	 `password` VARCHAR(65) NOT NULL,
	 `date_registered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

